### ISSUE TITLE
PixPlot output contains an embedded Google Analytics tracker

### ISSUE THREAD

**Issue by stijn-uva** [digitalmethodsinitiative/dmi_pix_plot#9]
It should not!

**Comment by dale-wahl** [comment]
Completely missed this issue. I removed the script from the `index.html` file in [this commit](https://github.com/digitalmethodsinitiative/dmi_pix_plot/commit/d2f22b1ba023b69dba6ee3f563f6a600a2f7d49b). Let me know if there are other parts of it lingering. 

When running the Docker image, it copies our application (which has the analytics tracker removed), but it also installs Yale's master version which [appears to have the tracker as of now.](https://github.com/YaleDHLab/pix-plot/blob/84afbd098f24c5a3ec41219fa849d3eb7b3dc57f/pixplot/web/index.html#L640) If you use the `yale_pixplot` endpoint, it will use that version (equivalent to running `docker exec pix_plot_container pixplot` vs ours at `docker exec pix_plot_container /app/pixplot/pixplot.py`).
